apiVersion: v1
kind: Service
metadata:
  name: {{ include "timescaledb.svc.headless" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: db
      port: {{ .Values.timescaledb.service.ports.db.port }}
      targetPort: {{ .Values.timescaledb.service.ports.db.targetPort }}
      protocol: {{ .Values.timescaledb.service.ports.db.protocol }}
  selector:
    {{- include "timescaledb.selectorLabels" . | nindent 4 }}