apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "timescaledb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "timescaledb.fullname" . }}-headless
  {{- if not .Values.timescaledb.autoscaling.enabled }}
  replicas: {{ .Values.timescaledb.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "timescaledb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "timescaledb.labels" . | nindent 8 }}
    spec:
      {{- with .Values.timescaledb.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chartNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.chartNodeSelector }}
        {{- with .Values.timescaledb.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.timescaledb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.timescaledb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.timescaledb.podSecurityContext | nindent 8 }}
      containers:
        - name: timescaledb
          securityContext:
            {{- toYaml .Values.timescaledb.securityContext | nindent 12 }}
          image: "{{ .Values.timescaledb.image.repository }}:{{ .Values.timescaledb.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.timescaledb.image.pullPolicy }}
          ports:
            - name: db
              containerPort: {{ .Values.timescaledb.service.ports.db.containerPort }}
              protocol: {{ .Values.timescaledb.service.ports.db.protocol }}
          resources:
            {{- toYaml .Values.timescaledb.resources | nindent 12 }}
          {{- with .Values.timescaledb.envVars }}
          env:
            - name: POSTGRES_USER
              value: {{ .user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .password | quote }}
            - name: POSTGRES_HOST_AUTH_METHOD
              value: {{ .hostAuthMethod | quote }}
          {{- end }}
          volumeMounts:
            {{- if .Values.timescaledb.persistence.enabled }}
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: data
            {{- end }}
      volumes:
  {{- if and .Values.timescaledb.persistence.enabled .Values.timescaledb.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.timescaledb.persistence.existingClaim $ }}
  {{- else if not .Values.timescaledb.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        {{- range .Values.timescaledb.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.timescaledb.persistence.size | quote }}
  {{- end }}
